// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cometbft/abci/v1/service.proto

package v1

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("cometbft/abci/v1/service.proto", fileDescriptor_728160d6a27c523b) }

var fileDescriptor_728160d6a27c523b = []byte{
	// 511 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x95, 0x4d, 0x6f, 0xd3, 0x30,
	0x18, 0xc7, 0x5b, 0x69, 0x0c, 0xe1, 0x09, 0x01, 0xe6, 0x36, 0x41, 0x18, 0x2f, 0xe2, 0x9d, 0x64,
	0x85, 0x13, 0xc7, 0x35, 0xca, 0x44, 0xb5, 0x69, 0x0c, 0x3a, 0x15, 0xc1, 0x89, 0x34, 0x7b, 0x42,
	0xac, 0xa6, 0xb1, 0xb1, 0x9d, 0xb2, 0xf2, 0x29, 0xf8, 0x50, 0x1c, 0x38, 0xee, 0xc8, 0x11, 0xb5,
	0x5f, 0x04, 0xa5, 0xb1, 0x29, 0x49, 0x5c, 0xaf, 0xd7, 0xe7, 0xff, 0xcb, 0xef, 0x6f, 0x47, 0x8f,
	0x64, 0xe4, 0x44, 0x74, 0x0c, 0x72, 0x18, 0x4b, 0x2f, 0x1c, 0x46, 0xc4, 0x9b, 0x74, 0x3c, 0x01,
	0x7c, 0x42, 0x22, 0x70, 0x19, 0xa7, 0x92, 0xe2, 0xeb, 0x3a, 0x77, 0x8b, 0xdc, 0x9d, 0x74, 0xb6,
	0x6f, 0x35, 0xbe, 0x90, 0x53, 0x06, 0xa2, 0xe4, 0x5f, 0xfe, 0xdc, 0x42, 0x5b, 0x7b, 0x5d, 0xbf,
	0xd7, 0x2f, 0x2d, 0x38, 0x40, 0x1b, 0x41, 0x94, 0x50, 0x7c, 0xdb, 0xad, 0x8b, 0xdc, 0x62, 0xfe,
	0x1e, 0xbe, 0xe6, 0x20, 0xe4, 0xb6, 0xb3, 0x2a, 0x16, 0x8c, 0x66, 0x02, 0xf0, 0x1b, 0x74, 0x69,
	0x3f, 0xcd, 0x45, 0x82, 0x0d, 0xe0, 0x22, 0xd0, 0xa2, 0x3b, 0x2b, 0x73, 0x65, 0x0a, 0xd0, 0x46,
	0x2f, 0x8b, 0x8d, 0x07, 0x2a, 0xe6, 0x96, 0x03, 0x95, 0xb1, 0xd2, 0x1c, 0xa1, 0xcb, 0x7e, 0x02,
	0xd1, 0xe8, 0xe4, 0x0c, 0xef, 0x34, 0x51, 0x15, 0x69, 0xd9, 0x5d, 0x0b, 0xb1, 0xbc, 0xe0, 0xbb,
	0x1c, 0xf8, 0xd4, 0x74, 0xc1, 0x45, 0x60, 0xb9, 0xa0, 0xca, 0x95, 0xe9, 0x00, 0x6d, 0xfa, 0x74,
	0x3c, 0x26, 0x12, 0x1b, 0xd0, 0x32, 0xd1, 0xae, 0x9d, 0xd5, 0x80, 0x92, 0x9d, 0xa0, 0x2b, 0xbd,
	0x8c, 0x48, 0x3f, 0x09, 0x49, 0x86, 0xef, 0x99, 0xfe, 0x89, 0x0a, 0xb5, 0xf2, 0xbe, 0x95, 0x51,
	0xd6, 0xcf, 0xe8, 0xea, 0x21, 0x11, 0xb2, 0x9f, 0x85, 0x4c, 0x24, 0x54, 0x0a, 0xfc, 0xb0, 0xf9,
	0x55, 0x05, 0xd0, 0xf6, 0x47, 0x17, 0x72, 0xcb, 0x86, 0xb7, 0x71, 0x0c, 0x5c, 0x27, 0xa6, 0x86,
	0x0a, 0x60, 0x69, 0xa8, 0x71, 0xaa, 0x21, 0x45, 0x37, 0x0e, 0x69, 0x78, 0xaa, 0xe7, 0x7e, 0x92,
	0x67, 0x23, 0xfc, 0xd4, 0x70, 0xbe, 0x3a, 0xa4, 0x9b, 0x9e, 0xad, 0xc5, 0xaa, 0x36, 0x8a, 0xf0,
	0x1e, 0x63, 0xe9, 0xb4, 0x5a, 0x67, 0x50, 0x34, 0x29, 0xdd, 0xf7, 0x7c, 0x3d, 0x58, 0x15, 0xc6,
	0xe8, 0xda, 0x31, 0x07, 0x16, 0x72, 0x38, 0xe6, 0x94, 0x51, 0x11, 0xa6, 0xf8, 0x71, 0x53, 0x50,
	0x43, 0x74, 0xd5, 0x93, 0x35, 0xc8, 0xff, 0x7b, 0x68, 0x04, 0x42, 0xd8, 0x7b, 0x2a, 0x88, 0xb5,
	0xa7, 0x46, 0xaa, 0x9e, 0x0f, 0x08, 0x05, 0x67, 0x12, 0xb2, 0xd3, 0x01, 0x95, 0x80, 0x0d, 0x5b,
	0xba, 0x4c, 0xb5, 0xfd, 0x81, 0x1d, 0x52, 0x62, 0x8e, 0x6e, 0x0e, 0x80, 0x93, 0x78, 0x5a, 0x4c,
	0x17, 0xb9, 0x20, 0x34, 0xc3, 0x86, 0xbf, 0x6d, 0xc0, 0x74, 0xd5, 0x8b, 0x35, 0xe9, 0xe5, 0x76,
	0xef, 0x93, 0x2c, 0x4c, 0xc9, 0x77, 0xe8, 0xa6, 0x34, 0x1a, 0x99, 0xb6, 0xbb, 0x02, 0x58, 0xb6,
	0xbb, 0xc6, 0x95, 0x0d, 0xdd, 0xfe, 0xaf, 0x99, 0xd3, 0x3e, 0x9f, 0x39, 0xed, 0x3f, 0x33, 0xa7,
	0xfd, 0x63, 0xee, 0xb4, 0xce, 0xe7, 0x4e, 0xeb, 0xf7, 0xdc, 0x69, 0x7d, 0x7a, 0xfd, 0x85, 0xc8,
	0x24, 0x1f, 0x16, 0x22, 0xef, 0xe0, 0xe3, 0x20, 0x38, 0x02, 0xf9, 0x8d, 0xf2, 0x91, 0xf7, 0xef,
	0x55, 0x98, 0x74, 0x76, 0x77, 0xbd, 0x90, 0x11, 0xaf, 0xfe, 0x4e, 0x0c, 0x37, 0x17, 0x4f, 0xc4,
	0xab, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x81, 0xda, 0x7b, 0xb8, 0x74, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ABCIServiceClient is the client API for ABCIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ABCIServiceClient interface {
	// Echo returns back the same message it is sent.
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	// Flush flushes the write buffer.
	Flush(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*FlushResponse, error)
	// Info returns information about the application state.
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
	// CheckTx validates a transaction.
	CheckTx(ctx context.Context, in *CheckTxRequest, opts ...grpc.CallOption) (*CheckTxResponse, error)
	// Query queries the application state.
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// Commit commits a block of transactions.
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
	// InitChain initializes the blockchain.
	InitChain(ctx context.Context, in *InitChainRequest, opts ...grpc.CallOption) (*InitChainResponse, error)
	// ListSnapshots lists all the available snapshots.
	ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error)
	// OfferSnapshot sends a snapshot offer.
	OfferSnapshot(ctx context.Context, in *OfferSnapshotRequest, opts ...grpc.CallOption) (*OfferSnapshotResponse, error)
	// LoadSnapshotChunk returns a chunk of snapshot.
	LoadSnapshotChunk(ctx context.Context, in *LoadSnapshotChunkRequest, opts ...grpc.CallOption) (*LoadSnapshotChunkResponse, error)
	// ApplySnapshotChunk applies a chunk of snapshot.
	ApplySnapshotChunk(ctx context.Context, in *ApplySnapshotChunkRequest, opts ...grpc.CallOption) (*ApplySnapshotChunkResponse, error)
	// PrepareProposal returns a proposal for the next block.
	PrepareProposal(ctx context.Context, in *PrepareProposalRequest, opts ...grpc.CallOption) (*PrepareProposalResponse, error)
	// ProcessProposal validates a proposal.
	ProcessProposal(ctx context.Context, in *ProcessProposalRequest, opts ...grpc.CallOption) (*ProcessProposalResponse, error)
	// ExtendVote extends a vote with application-injected data (vote extensions).
	ExtendVote(ctx context.Context, in *ExtendVoteRequest, opts ...grpc.CallOption) (*ExtendVoteResponse, error)
	// VerifyVoteExtension verifies a vote extension.
	VerifyVoteExtension(ctx context.Context, in *VerifyVoteExtensionRequest, opts ...grpc.CallOption) (*VerifyVoteExtensionResponse, error)
	// FinalizeBlock finalizes a block.
	FinalizeBlock(ctx context.Context, in *FinalizeBlockRequest, opts ...grpc.CallOption) (*FinalizeBlockResponse, error)
}

type aBCIServiceClient struct {
	cc grpc1.ClientConn
}

func NewABCIServiceClient(cc grpc1.ClientConn) ABCIServiceClient {
	return &aBCIServiceClient{cc}
}

func (c *aBCIServiceClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, "/cometbft.abci.v1.ABCIService/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIServiceClient) Flush(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*FlushResponse, error) {
	out := new(FlushResponse)
	err := c.cc.Invoke(ctx, "/cometbft.abci.v1.ABCIService/Flush", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIServiceClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, "/cometbft.abci.v1.ABCIService/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIServiceClient) CheckTx(ctx context.Context, in *CheckTxRequest, opts ...grpc.CallOption) (*CheckTxResponse, error) {
	out := new(CheckTxResponse)
	err := c.cc.Invoke(ctx, "/cometbft.abci.v1.ABCIService/CheckTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, "/cometbft.abci.v1.ABCIService/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIServiceClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, "/cometbft.abci.v1.ABCIService/Commit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIServiceClient) InitChain(ctx context.Context, in *InitChainRequest, opts ...grpc.CallOption) (*InitChainResponse, error) {
	out := new(InitChainResponse)
	err := c.cc.Invoke(ctx, "/cometbft.abci.v1.ABCIService/InitChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIServiceClient) ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error) {
	out := new(ListSnapshotsResponse)
	err := c.cc.Invoke(ctx, "/cometbft.abci.v1.ABCIService/ListSnapshots", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIServiceClient) OfferSnapshot(ctx context.Context, in *OfferSnapshotRequest, opts ...grpc.CallOption) (*OfferSnapshotResponse, error) {
	out := new(OfferSnapshotResponse)
	err := c.cc.Invoke(ctx, "/cometbft.abci.v1.ABCIService/OfferSnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIServiceClient) LoadSnapshotChunk(ctx context.Context, in *LoadSnapshotChunkRequest, opts ...grpc.CallOption) (*LoadSnapshotChunkResponse, error) {
	out := new(LoadSnapshotChunkResponse)
	err := c.cc.Invoke(ctx, "/cometbft.abci.v1.ABCIService/LoadSnapshotChunk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIServiceClient) ApplySnapshotChunk(ctx context.Context, in *ApplySnapshotChunkRequest, opts ...grpc.CallOption) (*ApplySnapshotChunkResponse, error) {
	out := new(ApplySnapshotChunkResponse)
	err := c.cc.Invoke(ctx, "/cometbft.abci.v1.ABCIService/ApplySnapshotChunk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIServiceClient) PrepareProposal(ctx context.Context, in *PrepareProposalRequest, opts ...grpc.CallOption) (*PrepareProposalResponse, error) {
	out := new(PrepareProposalResponse)
	err := c.cc.Invoke(ctx, "/cometbft.abci.v1.ABCIService/PrepareProposal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIServiceClient) ProcessProposal(ctx context.Context, in *ProcessProposalRequest, opts ...grpc.CallOption) (*ProcessProposalResponse, error) {
	out := new(ProcessProposalResponse)
	err := c.cc.Invoke(ctx, "/cometbft.abci.v1.ABCIService/ProcessProposal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIServiceClient) ExtendVote(ctx context.Context, in *ExtendVoteRequest, opts ...grpc.CallOption) (*ExtendVoteResponse, error) {
	out := new(ExtendVoteResponse)
	err := c.cc.Invoke(ctx, "/cometbft.abci.v1.ABCIService/ExtendVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIServiceClient) VerifyVoteExtension(ctx context.Context, in *VerifyVoteExtensionRequest, opts ...grpc.CallOption) (*VerifyVoteExtensionResponse, error) {
	out := new(VerifyVoteExtensionResponse)
	err := c.cc.Invoke(ctx, "/cometbft.abci.v1.ABCIService/VerifyVoteExtension", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBCIServiceClient) FinalizeBlock(ctx context.Context, in *FinalizeBlockRequest, opts ...grpc.CallOption) (*FinalizeBlockResponse, error) {
	out := new(FinalizeBlockResponse)
	err := c.cc.Invoke(ctx, "/cometbft.abci.v1.ABCIService/FinalizeBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ABCIServiceServer is the server API for ABCIService service.
type ABCIServiceServer interface {
	// Echo returns back the same message it is sent.
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	// Flush flushes the write buffer.
	Flush(context.Context, *FlushRequest) (*FlushResponse, error)
	// Info returns information about the application state.
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
	// CheckTx validates a transaction.
	CheckTx(context.Context, *CheckTxRequest) (*CheckTxResponse, error)
	// Query queries the application state.
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	// Commit commits a block of transactions.
	Commit(context.Context, *CommitRequest) (*CommitResponse, error)
	// InitChain initializes the blockchain.
	InitChain(context.Context, *InitChainRequest) (*InitChainResponse, error)
	// ListSnapshots lists all the available snapshots.
	ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error)
	// OfferSnapshot sends a snapshot offer.
	OfferSnapshot(context.Context, *OfferSnapshotRequest) (*OfferSnapshotResponse, error)
	// LoadSnapshotChunk returns a chunk of snapshot.
	LoadSnapshotChunk(context.Context, *LoadSnapshotChunkRequest) (*LoadSnapshotChunkResponse, error)
	// ApplySnapshotChunk applies a chunk of snapshot.
	ApplySnapshotChunk(context.Context, *ApplySnapshotChunkRequest) (*ApplySnapshotChunkResponse, error)
	// PrepareProposal returns a proposal for the next block.
	PrepareProposal(context.Context, *PrepareProposalRequest) (*PrepareProposalResponse, error)
	// ProcessProposal validates a proposal.
	ProcessProposal(context.Context, *ProcessProposalRequest) (*ProcessProposalResponse, error)
	// ExtendVote extends a vote with application-injected data (vote extensions).
	ExtendVote(context.Context, *ExtendVoteRequest) (*ExtendVoteResponse, error)
	// VerifyVoteExtension verifies a vote extension.
	VerifyVoteExtension(context.Context, *VerifyVoteExtensionRequest) (*VerifyVoteExtensionResponse, error)
	// FinalizeBlock finalizes a block.
	FinalizeBlock(context.Context, *FinalizeBlockRequest) (*FinalizeBlockResponse, error)
}

// UnimplementedABCIServiceServer can be embedded to have forward compatible implementations.
type UnimplementedABCIServiceServer struct {
}

func (*UnimplementedABCIServiceServer) Echo(ctx context.Context, req *EchoRequest) (*EchoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (*UnimplementedABCIServiceServer) Flush(ctx context.Context, req *FlushRequest) (*FlushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Flush not implemented")
}
func (*UnimplementedABCIServiceServer) Info(ctx context.Context, req *InfoRequest) (*InfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (*UnimplementedABCIServiceServer) CheckTx(ctx context.Context, req *CheckTxRequest) (*CheckTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckTx not implemented")
}
func (*UnimplementedABCIServiceServer) Query(ctx context.Context, req *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (*UnimplementedABCIServiceServer) Commit(ctx context.Context, req *CommitRequest) (*CommitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit not implemented")
}
func (*UnimplementedABCIServiceServer) InitChain(ctx context.Context, req *InitChainRequest) (*InitChainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitChain not implemented")
}
func (*UnimplementedABCIServiceServer) ListSnapshots(ctx context.Context, req *ListSnapshotsRequest) (*ListSnapshotsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSnapshots not implemented")
}
func (*UnimplementedABCIServiceServer) OfferSnapshot(ctx context.Context, req *OfferSnapshotRequest) (*OfferSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OfferSnapshot not implemented")
}
func (*UnimplementedABCIServiceServer) LoadSnapshotChunk(ctx context.Context, req *LoadSnapshotChunkRequest) (*LoadSnapshotChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadSnapshotChunk not implemented")
}
func (*UnimplementedABCIServiceServer) ApplySnapshotChunk(ctx context.Context, req *ApplySnapshotChunkRequest) (*ApplySnapshotChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplySnapshotChunk not implemented")
}
func (*UnimplementedABCIServiceServer) PrepareProposal(ctx context.Context, req *PrepareProposalRequest) (*PrepareProposalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareProposal not implemented")
}
func (*UnimplementedABCIServiceServer) ProcessProposal(ctx context.Context, req *ProcessProposalRequest) (*ProcessProposalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessProposal not implemented")
}
func (*UnimplementedABCIServiceServer) ExtendVote(ctx context.Context, req *ExtendVoteRequest) (*ExtendVoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExtendVote not implemented")
}
func (*UnimplementedABCIServiceServer) VerifyVoteExtension(ctx context.Context, req *VerifyVoteExtensionRequest) (*VerifyVoteExtensionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyVoteExtension not implemented")
}
func (*UnimplementedABCIServiceServer) FinalizeBlock(ctx context.Context, req *FinalizeBlockRequest) (*FinalizeBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinalizeBlock not implemented")
}

func RegisterABCIServiceServer(s grpc1.Server, srv ABCIServiceServer) {
	s.RegisterService(&_ABCIService_serviceDesc, srv)
}

func _ABCIService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cometbft.abci.v1.ABCIService/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIServiceServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIService_Flush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIServiceServer).Flush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cometbft.abci.v1.ABCIService/Flush",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIServiceServer).Flush(ctx, req.(*FlushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIService_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIServiceServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cometbft.abci.v1.ABCIService/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIServiceServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIService_CheckTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIServiceServer).CheckTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cometbft.abci.v1.ABCIService/CheckTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIServiceServer).CheckTx(ctx, req.(*CheckTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cometbft.abci.v1.ABCIService/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIService_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIServiceServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cometbft.abci.v1.ABCIService/Commit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIServiceServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIService_InitChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIServiceServer).InitChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cometbft.abci.v1.ABCIService/InitChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIServiceServer).InitChain(ctx, req.(*InitChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIService_ListSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIServiceServer).ListSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cometbft.abci.v1.ABCIService/ListSnapshots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIServiceServer).ListSnapshots(ctx, req.(*ListSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIService_OfferSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OfferSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIServiceServer).OfferSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cometbft.abci.v1.ABCIService/OfferSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIServiceServer).OfferSnapshot(ctx, req.(*OfferSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIService_LoadSnapshotChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadSnapshotChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIServiceServer).LoadSnapshotChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cometbft.abci.v1.ABCIService/LoadSnapshotChunk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIServiceServer).LoadSnapshotChunk(ctx, req.(*LoadSnapshotChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIService_ApplySnapshotChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplySnapshotChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIServiceServer).ApplySnapshotChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cometbft.abci.v1.ABCIService/ApplySnapshotChunk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIServiceServer).ApplySnapshotChunk(ctx, req.(*ApplySnapshotChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIService_PrepareProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIServiceServer).PrepareProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cometbft.abci.v1.ABCIService/PrepareProposal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIServiceServer).PrepareProposal(ctx, req.(*PrepareProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIService_ProcessProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIServiceServer).ProcessProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cometbft.abci.v1.ABCIService/ProcessProposal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIServiceServer).ProcessProposal(ctx, req.(*ProcessProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIService_ExtendVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtendVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIServiceServer).ExtendVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cometbft.abci.v1.ABCIService/ExtendVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIServiceServer).ExtendVote(ctx, req.(*ExtendVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIService_VerifyVoteExtension_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyVoteExtensionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIServiceServer).VerifyVoteExtension(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cometbft.abci.v1.ABCIService/VerifyVoteExtension",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIServiceServer).VerifyVoteExtension(ctx, req.(*VerifyVoteExtensionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABCIService_FinalizeBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABCIServiceServer).FinalizeBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cometbft.abci.v1.ABCIService/FinalizeBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABCIServiceServer).FinalizeBlock(ctx, req.(*FinalizeBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var ABCIService_serviceDesc = _ABCIService_serviceDesc
var _ABCIService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cometbft.abci.v1.ABCIService",
	HandlerType: (*ABCIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _ABCIService_Echo_Handler,
		},
		{
			MethodName: "Flush",
			Handler:    _ABCIService_Flush_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _ABCIService_Info_Handler,
		},
		{
			MethodName: "CheckTx",
			Handler:    _ABCIService_CheckTx_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _ABCIService_Query_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _ABCIService_Commit_Handler,
		},
		{
			MethodName: "InitChain",
			Handler:    _ABCIService_InitChain_Handler,
		},
		{
			MethodName: "ListSnapshots",
			Handler:    _ABCIService_ListSnapshots_Handler,
		},
		{
			MethodName: "OfferSnapshot",
			Handler:    _ABCIService_OfferSnapshot_Handler,
		},
		{
			MethodName: "LoadSnapshotChunk",
			Handler:    _ABCIService_LoadSnapshotChunk_Handler,
		},
		{
			MethodName: "ApplySnapshotChunk",
			Handler:    _ABCIService_ApplySnapshotChunk_Handler,
		},
		{
			MethodName: "PrepareProposal",
			Handler:    _ABCIService_PrepareProposal_Handler,
		},
		{
			MethodName: "ProcessProposal",
			Handler:    _ABCIService_ProcessProposal_Handler,
		},
		{
			MethodName: "ExtendVote",
			Handler:    _ABCIService_ExtendVote_Handler,
		},
		{
			MethodName: "VerifyVoteExtension",
			Handler:    _ABCIService_VerifyVoteExtension_Handler,
		},
		{
			MethodName: "FinalizeBlock",
			Handler:    _ABCIService_FinalizeBlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cometbft/abci/v1/service.proto",
}
