// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cometbft/v100/services/block/v1/block_service.proto

package v1

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("cometbft/v100/services/block/v1/block_service.proto", fileDescriptor_ace986fafa06822d)
}

var fileDescriptor_ace986fafa06822d = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4e, 0xce, 0xcf, 0x4d,
	0x2d, 0x49, 0x4a, 0x2b, 0xd1, 0x2f, 0x33, 0x34, 0x30, 0xd0, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c,
	0x4e, 0x2d, 0xd6, 0x4f, 0xca, 0xc9, 0x4f, 0xce, 0xd6, 0x2f, 0x33, 0x84, 0x30, 0xe2, 0xa1, 0xe2,
	0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xf2, 0x30, 0x4d, 0x7a, 0x20, 0x4d, 0x7a, 0x30, 0x4d,
	0x7a, 0x60, 0xb5, 0x7a, 0x65, 0x86, 0x52, 0xda, 0x44, 0x99, 0x0a, 0x31, 0xcd, 0x68, 0x22, 0x13,
	0x17, 0x8f, 0x13, 0x88, 0x1f, 0x0c, 0x51, 0x26, 0x54, 0xc1, 0xc5, 0xed, 0x9e, 0x5a, 0xe2, 0x54,
	0xe9, 0x91, 0x9a, 0x99, 0x9e, 0x51, 0x22, 0x64, 0xac, 0x47, 0xc0, 0x3a, 0x3d, 0x24, 0xd5, 0x41,
	0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x52, 0x26, 0xa4, 0x69, 0x2a, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e,
	0x15, 0x6a, 0x63, 0xe4, 0xe2, 0x77, 0x4f, 0x2d, 0xf1, 0x49, 0x2c, 0x49, 0x2d, 0x2e, 0x81, 0x5a,
	0x6f, 0x4e, 0x8c, 0x49, 0xc8, 0x3a, 0x60, 0x4e, 0xb0, 0x20, 0x5d, 0x23, 0xc4, 0x19, 0x06, 0x8c,
	0x4e, 0xb1, 0x27, 0x1e, 0xc9, 0x31, 0x5e, 0x78, 0x24, 0xc7, 0xf8, 0xe0, 0x91, 0x1c, 0xe3, 0x84,
	0xc7, 0x72, 0x0c, 0x17, 0x1e, 0xcb, 0x31, 0xdc, 0x78, 0x2c, 0xc7, 0x10, 0xe5, 0x9c, 0x9e, 0x59,
	0x92, 0x51, 0x9a, 0x04, 0x32, 0x5b, 0xdf, 0x3b, 0x32, 0xcc, 0xd5, 0x2f, 0xb5, 0xa4, 0x3c, 0xbf,
	0x28, 0x5b, 0x1f, 0x35, 0xc4, 0x13, 0x0b, 0x32, 0x11, 0x22, 0x18, 0xc1, 0x9f, 0xc4, 0x06, 0x0e,
	0x79, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8f, 0x18, 0x37, 0x83, 0xfe, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BlockServiceClient is the client API for BlockService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlockServiceClient interface {
	// GetBlock retrieves the block information at a particular height.
	GetByHeight(ctx context.Context, in *GetByHeightRequest, opts ...grpc.CallOption) (*GetByHeightResponse, error)
	// GetLatestHeight returns a stream of the latest block heights committed by
	// the network. This is a long-lived stream that is only terminated by the
	// server if an error occurs. The caller is expected to handle such
	// disconnections and automatically reconnect.
	GetLatestHeight(ctx context.Context, in *GetLatestHeightRequest, opts ...grpc.CallOption) (BlockService_GetLatestHeightClient, error)
}

type blockServiceClient struct {
	cc grpc1.ClientConn
}

func NewBlockServiceClient(cc grpc1.ClientConn) BlockServiceClient {
	return &blockServiceClient{cc}
}

func (c *blockServiceClient) GetByHeight(ctx context.Context, in *GetByHeightRequest, opts ...grpc.CallOption) (*GetByHeightResponse, error) {
	out := new(GetByHeightResponse)
	err := c.cc.Invoke(ctx, "/cometbft.v100.services.block.v1.BlockService/GetByHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockServiceClient) GetLatestHeight(ctx context.Context, in *GetLatestHeightRequest, opts ...grpc.CallOption) (BlockService_GetLatestHeightClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BlockService_serviceDesc.Streams[0], "/cometbft.v100.services.block.v1.BlockService/GetLatestHeight", opts...)
	if err != nil {
		return nil, err
	}
	x := &blockServiceGetLatestHeightClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BlockService_GetLatestHeightClient interface {
	Recv() (*GetLatestHeightResponse, error)
	grpc.ClientStream
}

type blockServiceGetLatestHeightClient struct {
	grpc.ClientStream
}

func (x *blockServiceGetLatestHeightClient) Recv() (*GetLatestHeightResponse, error) {
	m := new(GetLatestHeightResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BlockServiceServer is the server API for BlockService service.
type BlockServiceServer interface {
	// GetBlock retrieves the block information at a particular height.
	GetByHeight(context.Context, *GetByHeightRequest) (*GetByHeightResponse, error)
	// GetLatestHeight returns a stream of the latest block heights committed by
	// the network. This is a long-lived stream that is only terminated by the
	// server if an error occurs. The caller is expected to handle such
	// disconnections and automatically reconnect.
	GetLatestHeight(*GetLatestHeightRequest, BlockService_GetLatestHeightServer) error
}

// UnimplementedBlockServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBlockServiceServer struct {
}

func (*UnimplementedBlockServiceServer) GetByHeight(ctx context.Context, req *GetByHeightRequest) (*GetByHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByHeight not implemented")
}
func (*UnimplementedBlockServiceServer) GetLatestHeight(req *GetLatestHeightRequest, srv BlockService_GetLatestHeightServer) error {
	return status.Errorf(codes.Unimplemented, "method GetLatestHeight not implemented")
}

func RegisterBlockServiceServer(s grpc1.Server, srv BlockServiceServer) {
	s.RegisterService(&_BlockService_serviceDesc, srv)
}

func _BlockService_GetByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockServiceServer).GetByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cometbft.v100.services.block.v1.BlockService/GetByHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockServiceServer).GetByHeight(ctx, req.(*GetByHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockService_GetLatestHeight_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetLatestHeightRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlockServiceServer).GetLatestHeight(m, &blockServiceGetLatestHeightServer{stream})
}

type BlockService_GetLatestHeightServer interface {
	Send(*GetLatestHeightResponse) error
	grpc.ServerStream
}

type blockServiceGetLatestHeightServer struct {
	grpc.ServerStream
}

func (x *blockServiceGetLatestHeightServer) Send(m *GetLatestHeightResponse) error {
	return x.ServerStream.SendMsg(m)
}

var BlockService_serviceDesc = _BlockService_serviceDesc
var _BlockService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cometbft.v100.services.block.v1.BlockService",
	HandlerType: (*BlockServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByHeight",
			Handler:    _BlockService_GetByHeight_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetLatestHeight",
			Handler:       _BlockService_GetLatestHeight_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cometbft/v100/services/block/v1/block_service.proto",
}
